version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: practicas-hito3
    ports:
      - "1029:80"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
